# Generated by Django 6.0.3 on 2026-03-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='type',
            field=models.CharField(choices=[('verify', 'verify'), ('reset', 'Reset Password')], default='verify', max_length=10),
        ),
    ]
